swagger: "2.0"
info:
  title: Calculator Service
  description: Service for adding numbers, a Goa teaser
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - status
      summary: status status
      operationId: status#status
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /docs:
    get:
      tags:
      - status
      summary: Download ./gen/http/openapi.json
      operationId: status#/docs
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
